env: "localhost"

# 数据库配置
database:
  host: postgres
  port: 5478
  user: "postgres"
  password: "investool123"
  dbname: "fund"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300

# 业务相关配置
app:
  # 并发拉取数据时channel的大小
  chan_size: 1

  cronexp:
    # sync_fund: "0 6 * * 1-5"
    # sync_fund_managers: "0 5 * * 1-5"
    # sync_industry_list: "0 4 * * 1-5"
    sync_global_vars: "0 6 * * 1-5"

# server 相关配置
server:
  # server 运行地址，支持 HTTP 端口 ":port" 或 UNIX Socket "unix:/file"
  addr: ":9999"
  # gin mode ，可选值： debug 、 test 、 release
  mode: "debug"
  # 开启 pprof
  pprof: true
  # 开启 prometheus metrics
  metrics: true
  host_url: ""
