# Docker Compose for PostgreSQL
version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15
    container_name: fund_postgres
    restart: always
    environment:
      # 数据库名称
      POSTGRES_DB: fund
      # 数据库用户名
      POSTGRES_USER: postgres
      # 数据库密码
      POSTGRES_PASSWORD: investool123
      # PostgreSQL 配置
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      # 映射数据库端口
      - "5478:5432"
    volumes:
      # 数据持久化
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fund"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
